### ISSUE TITLE
Magicpaste does not seem to activate

### ISSUE THREAD

**Issue by adcousin** [evanfrawley/magicpaste#1]
Hi @evanfrawley, thanks for what looks like a precious webflow tool!
I feel quite thick because I can't get MagicPaste to work or activate in Chrome 99.0.4844.82 (latest version I guess).
Could you update the readme with a quick example of how to test it's properly working ?

My steps:
- Open webflow
- Create a random Rich text field
- Remove the sample content
- Add new content starting with @magicpaste
Something like:
```markdown
@magicpaste
H1. Text header
H2. Text header 2
[Some link](www.example.com)
```
- Wait 😆 
- Not seeing anything new

Should you have some time to have a look at my request, I'll be glad!
Cheers

**Comment by evanfrawley** [comment]
Hey there. It looks like you're not writing syntactically correct markdown!

Try the following:

```
@magicpaste 

# heading 1 

## heading 2

[some link](https://google.com)
```

Markdown is a bit weird in that the headings need to have newline spaces in between them. Not sure why but that's just how markdown is ¯\\\_(ツ)\_/¯

**Comment by adcousin** [comment]
Thanks a lot, that works.
